Fwa 010 get city api
heupotato/flutter-weather-app pull request #11
Opened 2021-07-28 10:47 UTC by heupotato

2021-08-02 10:12 UTC, lngyeen requested changes
Resolve conflicts please.

2021-08-04 10:40 UTC, heupotato commented
Resolved conflicts

2021-08-05 03:31 UTC, lngyeen approved these changes

2021-08-05 03:31 UTC, lngyeen commented on Flutter_Weather/lib/widgets/weather_detail_box_widget.dart
> +                    child: WeatherTypeIcon(weather: todayWeather.weatherNow!.weather),
Avoid force unwrap optional value: 'weatherNow!'. Check if it's not null first.

2021-08-05 03:31 UTC, merged