Fwa 004 handle data from json
heupotato/flutter-weather-app pull request #4
Opened 2021-07-08 04:49 UTC by heupotato

2021-07-08 05:44 UTC, lngyeen requested changes

2021-07-08 05:44 UTC, lngyeen commented on Flutter_Weather/assets/jsons/mock_json_data.json
> +﻿{
File name should describe file contents. (Should be 'mock_weather.json')

2021-07-08 05:44 UTC, lngyeen commented on Flutter_Weather/jsons/mockjsondata.json
> +{
This is a json data model file,  not a mock data file. So the name should be 'weather.json'

2021-07-08 05:44 UTC, lngyeen commented on Flutter_Weather/lib/models/weather_data.dart
> +class Wind10m {
Should create json file 'wind10m.json' put it in jsons/ folder. So json_to_model will generate separated files for each model. Easy to maintain code.

2021-07-08 05:44 UTC, lngyeen commented on Flutter_Weather/lib/storage/json_repositories/weather_data_repository.dart
> +  DateTime getInitDate() => DateFormatter.yearMonthDayHour(init);//DateFormatter.yearMonthDay(init.substring(0, init.length -2));
Should be get property, not function: 'DateTime get initDate => /...'

2021-07-08 05:44 UTC, lngyeen commented on Flutter_Weather/lib/storage/json_repositories/weather_data_repository.dart
> +  DateTime getTrueDate(int timePoint) => this.getInitDate().add(Duration(hours: timePoint));
Same above, should be get property

2021-07-08 05:44 UTC, lngyeen commented on Flutter_Weather/lib/storage/json_repositories/weather_data_repository.dart
> +  List<DateTime> getTrueDates(List<WeatherData> dataList)
same above

2021-07-08 05:44 UTC, lngyeen commented on Flutter_Weather/lib/storage/json_repositories/weather_data_repository.dart
> +  List<String> getWeekDays(List<WeatherData> dataList)
same above

2021-07-08 05:44 UTC, lngyeen commented on Flutter_Weather/lib/storage/json_repositories/weather_data_repository.dart
> +  List<WeatherData> getDayData(){
Day data some time have only 1 or 2 timePoints. You should create a class 'DayWeather' to handle this.

2021-07-08 05:44 UTC, lngyeen commented on Flutter_Weather/lib/storage/json_repositories/weather_data_repository.dart
> +  List<WeatherData> getWeekData(){
Should create class 'WeekWeather' contains List of DayWeather to handle data for a week.

2021-07-08 06:36 UTC, lngyeen requested changes

2021-07-08 06:36 UTC, lngyeen commented on Flutter_Weather/lib/services/date_formatter.dart
> +  static DateTime yearMonthDayHour(String initDate){
Should move to Weather class extension, This special value handling occurs only in that class, it is specific to that class.

2021-07-13 02:26 UTC, lngyeen commented
Resolve conflicts.

2021-07-13 02:44 UTC, heupotato commented
Conflicts resolved

2021-07-13 02:45 UTC, merged